{% set version = "1.1.1" %}
{% set build_number = 3 %}

package:
  name: einsums-split
  version: {{ version }}

source:
  url: https://github.com/Einsums/Einsums/archive/v{{ version }}.tar.gz
  sha256: d2d98be0748cbec3a8076cf42b005fa1f9d794a403f1e0622477d2244f4e1e2b

build:
  number: {{ build_number }}
  binary_relocation: true
  skip: true  # [win]

outputs:
  - name: einsums
    script: build-cxx.sh
    build:
      run_exports:
        - {{ pin_subpackage('einsums', max_pin='x.x') }}

    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake 3.29.*                           # 3.30 failing for intel mac
        - ninja
        - catch2
      host:
        - hdf5
        - libblas
        - liblapack
        - llvm-openmp                            # [osx]
        - libgomp                                # [linux]
        - fftw
        - fmt
        - cpp-argparse
        - spdlog
        - zlib
        - cpptrace
      run:
        - cpp-argparse

    test:
      commands:
        # Verify library
        - test -f $PREFIX/lib/libEinsums$SHLIB_EXT                             # [unix]
        - test ! -f $PREFIX/lib/libEinsums.a                                   # [unix]
        - test -f $PREFIX/lib/libEinsumsExperimental$SHLIB_EXT                 # [unix]
        - test ! -f $PREFIX/lib/libEinsumsExperimental.a                       # [unix]
        # Verify accessories
        - test -f $PREFIX/include/Einsums/Tensor.hpp                           # [unix]
        - test -f $PREFIX/include/Einsums/h5cpp/H5Pall.hpp                     # [unix]
        - test -f $PREFIX/share/cmake/Einsums/EinsumsConfig.cmake              # [unix]
        - test -f $PREFIX/share/cmake/Einsums/EinsumsTargets.cmake             # [unix]
        # Inspect linkage
        - ldd -v $PREFIX/lib/libEinsums$SHLIB_EXT                              # [linux]
        - otool -L $PREFIX/lib/libEinsums$SHLIB_EXT                            # [osx]

about:
  home: https://github.com/Einsums/Einsums
  dev_url: https://github.com/Einsums/Einsums
  doc_url: https://einsums.github.io/Einsums
  license: MIT AND BSD-3-Clause
  license_url: https://opensource.org/license/mit/
  license_file:
    - LICENSE.txt
    - THIRD-PARTY-LICENSES.txt
  license_family: MIT
  summary: "J. Turney's C++ library providing compile-time contraction pattern analysis to determine optimal tensor operations"

extra:
  feedstock-name: einsums
  recipe-maintainers:
    - loriab
    - jturney
