{% set version = "1.1.2" %}
{% set build_number = 1 %}

package:
  name: einsums-split
  version: {{ version }}

source:
  url: https://github.com/Einsums/Einsums/archive/v{{ version }}.tar.gz
  sha256: 73f43a6b10780e5cca7149c55c2fd5b03ce4269b56fdd2cc83e949a025bde8f7

build:
  number: {{ build_number }}
  binary_relocation: true
  skip: true  # [win]

outputs:
  - name: einsums
    script: build-cxx.sh
    build:
      run_exports:
        - {{ pin_subpackage('einsums', max_pin='x.x') }}

    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - cmake
        - ninja
        - catch2
      host:
        - hdf5
        - libblas
        - liblapack
        - llvm-openmp                            # [osx]
        - libgomp                                # [linux]
        - fftw
        - fmt
        - cpp-argparse
        - spdlog
        - zlib
        - cpptrace
      run:
        - cpp-argparse

    test:
      commands:
        # Verify library
        - test -f $PREFIX/lib/libEinsums$SHLIB_EXT                             # [unix]
        - test ! -f $PREFIX/lib/libEinsums.a                                   # [unix]
        - test -f $PREFIX/lib/libEinsumsExperimental$SHLIB_EXT                 # [unix]
        - test ! -f $PREFIX/lib/libEinsumsExperimental.a                       # [unix]
        # Verify accessories
        - test -f $PREFIX/include/Einsums/Tensor.hpp                           # [unix]
        - test -f $PREFIX/include/Einsums/h5cpp/H5Pall.hpp                     # [unix]
        - test -f $PREFIX/share/cmake/Einsums/EinsumsConfig.cmake              # [unix]
        - test -f $PREFIX/share/cmake/Einsums/EinsumsTargets.cmake             # [unix]
        # Inspect linkage
        - ldd -v $PREFIX/lib/libEinsums$SHLIB_EXT                              # [linux]
        - otool -L $PREFIX/lib/libEinsums$SHLIB_EXT                            # [osx]

  - name: pyeinsums
    script: build-py.sh
    build:
      ignore_run_exports_from:
        - libblas
        - liblapack
        - fftw
        - cpp-argparse
        - zlib
        - cpptrace
      # skip: true                                                               # [py != 312]

    requirements:
      build:
        - {{ stdlib("c") }}                                                    # [unix]
        - {{ compiler("c") }}                                                  # [unix]
        - {{ compiler("cxx") }}                                                # [unix]
        - cmake
        - ninja
        - catch2
        - python                                                               # [build_platform != target_platform]
        - cross-python_{{ target_platform }}                                   # [build_platform != target_platform]
        - numpy                                                                # [build_platform != target_platform]
        - pybind11                                                             # [build_platform != target_platform]
      host:
        - python
        - pybind11
        - pybind11-abi
        - numpy
        - llvm-openmp                                                          # [osx]
        - libgomp                                                              # [linux]
        # to rebuild the c++ lib
        - hdf5
        - libblas
        - liblapack
        - fftw
        - fmt
        - cpp-argparse
        - spdlog
        - zlib
        - cpptrace
        - {{ pin_subpackage('einsums', exact=True) }}
      run:
        - {{ pin_subpackage('einsums', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}

    test:
      requires:
        - pytest-xdist
        - scipy
      imports:
        - einsums
      commands:
        # Verify module
        - test -f $SP_DIR/einsums/core*.so                                     # [unix]
        - if not exist %SP_DIR%\\einsums\\core*.pyd exit 1                     # [win]
        # Verify accessories
        # Inspect linkage
        - ldd -v $SP_DIR/einsums/core*.so                                      # [linux and build_platform == target_platform]
        - otool -L $SP_DIR/einsums/core*.so                                    # [osx]
        # Actually test
        - pytest -v -rws --color yes --durations 10 -n auto -k "not 1000" $SP_DIR/einsums    # [unix]
        - pytest -v -rws --color yes --durations 10 -n auto -k "not 1000" %SP_DIR%\\einsums  # [win]

about:
  home: https://github.com/Einsums/Einsums
  dev_url: https://github.com/Einsums/Einsums
  doc_url: https://einsums.github.io/Einsums
  license: MIT AND BSD-3-Clause
  license_url: https://opensource.org/license/mit/
  license_file:
    - LICENSE.txt
    - THIRD-PARTY-LICENSES.txt
  license_family: MIT
  summary: "J. Turney's C++ library providing compile-time contraction pattern analysis to determine optimal tensor operations"

extra:
  feedstock-name: einsums
  recipe-maintainers:
    - loriab
    - jturney
